/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { OldWavePortal } from "./OldWavePortal";
export type { WavePortal } from "./WavePortal";

export { OldWavePortal__factory } from "./factories/OldWavePortal__factory";
export { WavePortal__factory } from "./factories/WavePortal__factory";
